# -*- coding: utf-8 -*-
#
# Problem Solving with Algorithms and Data Structures documentation build configuration file, created by
# sphinx-quickstart on Thu Oct 27 08:17:45 2011.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os
from runestone import runestone_static_dirs, runestone_extensions
extensions = ['sphinx.ext.mathjax', 'sphinx.ext.githubpages', 'sphinxcontrib.programoutput'] + runestone_extensions()
templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'
project = 'Informática para ingenieros'
copyright = '2017 Francisco Moya'
version = '0.0.1'
release = '0.0'
exclude_patterns = []
# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False
pygments_style = 'sphinx'
html_theme = 'sphinx_bootstrap'
html_theme_options = {
    'navbar_title': "Informática",
    'navbar_site_name': "Capítulos",
    'globaltoc_depth': 1,
    'globaltoc_includehidden': "true",
    'navbar_class': "navbar",
    'navbar_fixed_top': "true",
    'source_link_position': "nav",
    'bootswatch_theme': "",
}

html_theme_path = ["_templates/plugin_layouts"]
html_title = None
html_short_title ='Informática'
html_logo = "_static/eii.png"
html_favicon = "_static/favicon.ico"
html_static_path = ['_static']  + runestone_static_dirs()
html_show_sourcelink = True
html_show_sphinx = False
htmlhelp_basename = 'help'
language = 'es'
today_fmt = '%d de %B de %Y'
course_id = 'CS101'

